spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    device-data: ${KAFKA_TOPIC_DEVICE_DATA}

core-service:
  url: ${CORE_SERVICE_URL}

logging:
  level:
    com.devicemind.broker: INFO
    io.netty: WARN
