spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 10
      delivery-timeout-ms: 30000
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        min.insync.replicas: 2
        request.timeout.ms: 10000
        retry.backoff.ms: 500
        linger.ms: 10
        batch.size: 16384
        compression.type: snappy
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 3000

kafka:
  topic:
    replicas: 3
    min-isr: 2
  topics:
    device-data: ${KAFKA_TOPIC_DEVICE_DATA}
    device-lifecycle: ${KAFKA_TOPIC_DEVICE_LIFECYCLE}
    device-status: ${KAFKA_TOPIC_DEVICE_STATUS}
    device-command: ${KAFKA_TOPIC_DEVICE_COMMAND}
    device-response: ${KAFKA_TOPIC_DEVICE_RESPONSE}
core-service:
  url: ${CORE_SERVICE_URL}

broker:
  auth:
    enabled: ${BROKER_AUTH_ENABLED}
    username: ${BROKER_AUTH_USERNAME}
    password: ${BROKER_AUTH_PASSWORD}

logging:
  level:
    com.devicemind.broker: INFO
    io.netty: WARN
