server:
  port: 8081
  servlet:
    context-path: /device-mind/agent

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  file:
    name: ${LOG_PATH:./logs}/agent.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
